//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Foods = new HashSet<Food>();
        }
    
        public int id { get; set; }
        public string status { get; set; }
        public System.DateTime order_time { get; set; }
        public string expire_time { get; set; }
        public int total_quantity { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> admin_id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Food> Foods { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
